### ISSUE TITLE
nearest_node = self.robot.node_manager.nodes_dict.nearest_neighbors(self.robot_location.tolist(), 1)[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by tqlblzj** [marmotlab/ARiADNE-ROS-Planner#1]
Hi, thanks for your open source code, here i have a question, when i launch the code, the error is 

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/dzt/anaconda3/envs/drl/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 237, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/home/dzt/catkin_ws/ARiADNE-ROS-Planner/src/scripts/rl_planner.py", line 208, in run
    nearest_node = self.robot.node_manager.nodes_dict.nearest_neighbors(self.robot_location.tolist(), 1)[0]
IndexError: list index out of range

This shows that at first there is no any way_point, can you help me solve it, thanks!!!

**Comment by caoyuhong001** [comment]
This is because I assume the robot starts at (0,0) wrt to the map frame, where I initialize the quad tree. Could you check the start location of your robot? I guess you are using a customized environment.

**Comment by cbcbHH** [comment]
> This is because I assume the robot starts at (0,0) wrt to the map frame, where I initialize the quad tree. Could you check the start location of your robot? I guess you are using a customized environment.

 Hello, I have met the same problems; However, I used the same environment developed by CMU, where I changed the robot position from a random start.  I have found that the problems were from the quad tree in quad.py, and I tried to initialize the tree from the start location of the robot, but it still showed the error "AttributeError: 'NoneType' object has no attribute 'data' ". Could you please help me to address this problem, thanks a lot !!! Appreciate your greatness.

**Comment by caoyuhong001** [comment]
I have updated the code to support random starting locations as requst by @cbcbHH. You can try wheter it solves your issue as well.
